name: Clean

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 0"

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Delete releases
        uses: apoiston/actions@cleaner
        with:
          enable_delete_releases: true
