name: test

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date +"%Y-%m-%d %H:%M:%S"
        env:
          TZ: Asia/Shanghai
                    
      - name: system info
        run: |
          date +"%Y-%m-%d %H:%M:%S"
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: apoiston/actions@world
        with:
          config_buildinfo: config/config.buildinfo
          private-key: ${{ secrets.PRIVATE_KEY }}
          public-key: ${{ secrets.PUBLIC_KEY }}
          prepare_compile: ${{ secrets.PREPARE_COMPILE }}
          prepare_configure: ${{ secrets.PREPARE_CONFIGURE }}
          prepare_world: ${{ secrets.PREPARE_WORLD }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            ./openwrt/apps/*
            ./openwrt/apps.tar.gz